Repository MixUpTeam/MixUpFront, pull requests merged in 2020-06, with the labels that each got.

#24 12-18 track search bar component v1
  package-lock.json
  package.json
  src/pages/Playlist/index.jsx
  src/pages/Playlist/styles.scss
  src/services/APIManager/index.jsx
  yarn.lock
Labels: front

#36 16 components up vote btn and down vote btn
  src/pages/NewPlaylist/index.jsx
  src/pages/Playlist/index.jsx
  src/services/APIManager/index.jsx
  src/tools/Dislikes/index.jsx
  src/tools/Likes/index.jsx
Labels: front

#38 [add] sort by score and updated_at time
  src/pages/Playlist/index.jsx
Labels: front

#40 #39 store track playlists into states for live changing
  README.md
  src/pages/Playlist/index.jsx
  src/redux/index.js
  src/redux/store.js
  src/redux/tracklist/tracklistActions.js
  src/redux/tracklist/tracklistReducer.js
  src/redux/tracklist/tracklistType.js
  src/services/APIManager/index.jsx
  src/tools/Dislikes/index.jsx
  src/tools/Likes/index.jsx
Labels: front

#41 #32 function interaction with spotify
  src/pages/Playlist/index.jsx
  src/services/SpotifyAPIManager/index.js
Labels: front

#43 #26 summary tracks table of a playlist
  package-lock.json
  package.json
  src/components/PlaylistTable/index.jsx
  src/pages/Playlist/index.jsx
  src/services/SpotifyAPIManager/index.js
Labels: front

#50 #48 fixed bug with new playlist by cleaning redux store trackList
  src/pages/Playlist/index.jsx
Labels: front

#52 29 function user auth
  src/App.jsx
  src/components/Navbar/index.jsx
  src/components/PlaylistTable/index.jsx
  src/constants/index.js
  src/pages/Home/index.jsx
  src/pages/Login/index.jsx
  src/pages/NewPlaylist/index.jsx
  src/pages/Playlist/index.jsx
  src/pages/Register/index.jsx
  src/redux/log/logReducer.js
  src/redux/user/userReducer.js
  src/services/APIManager/index.jsx
  src/services/SpotifyAPIManager/index.js
  src/tools/Authroute/index.jsx
Labels: front

#55 54 error handling for axios
  src/components/Navbar/index.jsx
  src/components/PlaylistTable/index.jsx
  src/pages/Login/index.jsx
  src/pages/NewPlaylist/index.jsx
  src/pages/Playlist/index.jsx
  src/pages/Register/index.jsx
  src/services/SpotifyAPIManager/index.js
Labels: front

#57 #53 display song
  package.json
  src/components/Player/index.jsx
  src/pages/Playlist/index.jsx
  src/services/SpotifyAPIManager/index.js
  yarn.lock
Labels: front

#58 #33 Renew spotify token
  src/App.jsx
  src/components/PlaylistTable/index.jsx
  src/constants/index.js
  src/services/APIManager/index.jsx
  src/services/SpotifyAPIManager/index.js
  src/services/SpotifyAuthManager/index.js
Labels: front

#61 hot-fix-jwt-token
  src/services/APIManager/index.jsx
Labels: front

#64 hot-fix handle undefined cookies
  src/services/APIManager/index.jsx
Labels: front

#63 [edit] design of the playlist table
  src/components/PlaylistTable/index.jsx
  src/components/PlaylistTable/styles.scss
Labels: front

#65 #27 table scrollable with all tracks visible
  src/components/PlaylistTable/index.jsx
  src/components/PlaylistTable/styles.scss
Labels: front

#70 27 responsive css
  public/favicon.ico
  public/favicon.png
  public/index.html
  src/App.jsx
  src/assets/scss/_variables.scss
  src/assets/scss/forms.scss
  src/assets/scss/styles.scss
  src/components/Navbar/index.jsx
  src/components/Player/index.jsx
  src/components/PlaylistTable/index.jsx
  src/pages/Home/styles.scss
  src/pages/Login/index.jsx
  src/pages/Login/style.scss
  src/pages/NewPlaylist/styles.scss
  src/pages/Playlist/index.jsx
  src/pages/Playlist/styles.scss
  src/pages/Register/index.jsx
  src/redux/log/logReducer.js
  src/redux/store.js
  src/tools/Authroute/index.jsx
Labels: front

#69 #67 function chaining tracks with player v2
  src/components/Player/index.jsx
  src/pages/Playlist/index.jsx
  src/redux/index.js
  src/redux/tracklist/tracklistActions.js
  src/redux/tracklist/tracklistReducer.js
  src/redux/tracklist/tracklistType.js
  src/services/APIManager/index.jsx
Labels: front

#68 #60 play several songs in a row
  package-lock.json
  package.json
  src/components/Player/index.jsx
  src/components/Player/styles.scss
  src/pages/Playlist/index.jsx
Labels: front

#72 PWA
  public/index.html
  public/main.js
  public/manifest.json
  public/worker.js
  src/assets/images/mix_up_logo_128.png
  src/assets/images/mix_up_logo_144.png
  src/assets/images/mix_up_logo_152.png
  src/assets/images/mix_up_logo_16.png
  src/assets/images/mix_up_logo_192.png
  src/assets/images/mix_up_logo_256.png
  src/assets/images/mix_up_logo_512.png
  src/index.jsx
Labels: front, minor

#73 Relay
  src/components/Player/index.jsx
  src/pages/Playlist/index.jsx
Labels: front, priority

#74 #71 readme
  README.md
Labels: front

#75 67 separate current track from track list
  src/components/Player/index.jsx
  src/components/PlaylistTable/index.jsx
  src/pages/Playlist/index.jsx
  src/services/APIManager/index.jsx
Labels: front

#76 update master with latest status in development
  package-lock.json
  package.json
  src/components/Player/index.jsx
  src/components/Player/styles.scss
  src/components/PlaylistTable/index.jsx
  src/pages/Playlist/index.jsx
  src/pages/Playlist/styles.scss
  src/redux/index.js
  src/redux/tracklist/tracklistActions.js
  src/redux/tracklist/tracklistReducer.js
  src/redux/tracklist/tracklistType.js
  src/services/APIManager/index.jsx
Labels: front

#78 #77 render view playlist table back order
  src/components/Player/index.jsx
  src/components/PlaylistTable/index.jsx
  src/constants/index.js
  src/pages/NewPlaylist/index.jsx
  src/pages/Playlist/index.jsx
  src/redux/index.js
  src/redux/tracklist/tracklistActions.js
  src/redux/tracklist/tracklistReducer.js
  src/redux/tracklist/tracklistType.js
  src/services/APIManager/index.jsx
Labels: front

#82 81 process env
  .env
  .eslintrc.json
  .gitignore
  README.md
  public/index.html
  src/components/Player/index.jsx
  src/components/PlaylistTable/index.jsx
  src/constants/index.js
  src/pages/Playlist/styles.scss
  src/services/SpotifyAPIManager/index.js
Labels: front

#83 [fixup] path into index.jsx for vercel deployment
  .gitignore
  src/.env
  src/App.jsx
  src/components/Navbar/index.jsx
  src/components/Player/index.jsx
  src/components/PlaylistTable/index.jsx
  src/components/ShareButton/index.jsx
  src/constants/index.js
  src/index.jsx
  src/pages/Home/index.jsx
  src/pages/Login/index.jsx
  src/pages/NewPlaylist/index.jsx
  src/pages/Playlist/index.jsx
  src/pages/Register/index.jsx
  src/redux/index.js
  src/redux/log/logActions.js
  src/redux/log/logReducer.js
  src/redux/store.js
  src/redux/tracklist/tracklistActions.js
  src/redux/tracklist/tracklistReducer.js
  src/redux/user/userActions.js
  src/redux/user/userReducer.js
  src/services/SpotifyAPIManager/index.js
  src/tools/Authroute/index.jsx
Labels: front

#84 Vercel 2
  .env
  src/.env
  src/constants/index.js
  src/services/APIManager/index.jsx
Labels: front

#85 [delete] trailing .env
  .env
Labels: DevOps

#86 Update token
  src/constants/index.js
Labels: front
